apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/bruno-Practicas/tfm-ai/refs/heads/main/k8s/03-ingress.yaml
  - https://raw.githubusercontent.com/bruno-Practicas/tfm-ai/refs/heads/main/k8s/02-service.yaml
  - https://raw.githubusercontent.com/bruno-Practicas/tfm-ai/refs/heads/main/k8s/01-deployment.yaml
  - https://raw.githubusercontent.com/bruno-Practicas/tfm-ai/refs/heads/main/k8s/00-secret.yaml

patches:
  - target:
      kind: Ingress
      name: frontend-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: fabio.helmcode.com 
      
      - op: replace
        path: /spec/tls/0/hosts/0
        value: fabio.helmcode.com 
  - target:
      kind: Deployment
      name: tfm-ai
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: tfm-ai
      spec:
        template:
          spec:
            containers:
              - name: tfm-ai
                env:
                  - name: VITE_API_KEY 
                    valueFrom:
                      secretKeyRef:
                        name: tfm-ai-api-secrets 
                        key: MASTER_API_KEY