apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tfm-ai

resources:
  - https://raw.githubusercontent.com/bruno-Practicas/tfm-ai/refs/heads/main/k8s/middleware.yaml
  - https://raw.githubusercontent.com/bruno-Practicas/tfm-ai/refs/heads/main/k8s/service.yaml
  - https://raw.githubusercontent.com/bruno-Practicas/tfm-ai/refs/heads/main/k8s/deployment.yaml
  - https://raw.githubusercontent.com/bruno-Practicas/tfm-ai/refs/heads/main/k8s/ingressroute.yaml

patches:
  - target:
      kind: IngressRoute
      name: tfm-ai-http
    patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`fabio.helmcode.com`)
      - op: replace
        path: /spec/routes/0/services/0/name
        value: tfm-ai
      
  - target:
      kind: IngressRoute
      name: tfm-ai-https
    patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`fabio.helmcode.com`)
      - op: replace
        path: /spec/routes/0/services/0/name
        value: tfm-ai
#test